name: update-goals
on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/15 * * * *'
jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup-node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: cache-npm-dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: install-cli
        run: |
          npm install -g notion-board-box
      - name: run-script
        run: |
          notion-board-box --id=1c056f78822c2d6b87d11410adaa8e1a --page=9d274b2fc30444358ef988c0d1d884b8 --url=[goals.unix.bio](https://goals.unix.bio/)
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
